baseURL = "https://vmwarefusion.github.io/"
languageCode = "en-us"
title = "VMware Fusion GitHub"
theme = "vmf-hugo"
summaryLength = "10"
paginate = 6

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.carousel.min.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.theme.green.min.css"
  [[params.plugins.css]]
  URL = "plugins/fancybox/jquery.fancybox.min.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/owl-carousel/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "plugins/fancybox/jquery.fancybox.min.js"
  [[params.plugins.js]]
  URL = "plugins/syotimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "GitHub"
  URL = "https://github.com/VMwareFusion"
  weight = 2
  
  [[menu.main]]
  name = "Getting Started"
  URL = "https://github.com/VMwareFusion/nautilus/blob/master/docs/getting-started.md"
  weight = 3

  [[menu.main]]
  name = "Beta Community"
  URL = "https://communities.vmware.com/community/vmtn/beta/fusion-pro"
  weight = 4
  
  [[menu.main]]
  name = "Blog"
  URL = "https://blogs.vmware.com/teamfusion"
  weight = 5
  
  [[menu.main]]
  name = "Docs"
  URL = "https://github.com/VMwareFusion/nautilus/tree/master/docs"
  weight = 6
  

  # footer menu
  [[menu.footer]]
  name = "Getting Started"
  URL = "https://github.com/VMwareFusion/nautilus/blob/master/docs/getting-started.md"
  
  [[menu.footer]]
  name = "Nautilus FAQs"
  URL = "https://github.com/VMwareFusion/nautilus/blob/master/docs/FAQ.md"
  
  [[menu.footer]]
  name = "Blog"
  URL = "https://blogs.vmware.com/teamfusion"
  
  [[menu.footer]]
  name = "Fusion Community"
  URL = "https://communities.vmware.com/community/vmtn/fusion"
  
  [[menu.footer]]
  name = "Tech Preview Community"
  URL = "https://communities.vmware.com/community/beta/fusion-pro"


[params]
logo = "images/logo.png"
logoAlt = "images/logo-alt.png"
home = "Home"
# Meta data
description = "Fusion GitHub Org theme"
author = "Michael Roy, but I just tweaked a theme"

googleAnalitycsID = "not installed"

  # Preloader
  [params.preloader]
  enable = true

  # social icon
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-facebook"
  URL = "https://facebook.com/vmwarefusion"

  [[params.footer.socialIcon]]
  icon = "tf-ion-social-twitter"
  URL = "https://twitter.com/vmwarefusion"
  
